# Generated by Django 4.2.3 on 2024-08-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='category_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='note_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory_thumbnails/'),
        ),
    ]
