# Generated by Django 4.2.3 on 2024-08-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_category_thumbnail_alter_note_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='accessibility',
        ),
        migrations.AddField(
            model_name='note',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7),
        ),
        migrations.DeleteModel(
            name='Accessibility',
        ),
    ]
