# Generated by Django 4.2.3 on 2024-08-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_accessibility_note_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='notes', to='notes.tag'),
        ),
    ]
